// Sva pitanja i odgovori za ispit Voditelj brodice kategorije B
// 5 kategorija, ~156 pitanja. Svaki unos ima: kratko (sažetak za brzo učenje) i puni odgovor.

const KATEGORIJE = [
  { id: "nav", naziv: "Navigacija", emoji: "🧭" },
  { id: "mot", naziv: "Motoristika", emoji: "⚙️" },
  { id: "pom", naziv: "Pomorstvo, propisi i meteorologija", emoji: "📜" },
  { id: "man", naziv: "Manevriranje, sigurnost i prva pomoć", emoji: "⚓" },
  { id: "rtf", naziv: "Radiotelefonija", emoji: "📻" },
];

const PITANJA = [
  // ===================== 1) NAVIGACIJA =====================
  { kat: "nav", p: "Kako se mjeri udaljenost između dvije točke na karti?",
    kratko: "Šestarom obuhvati razmak → prenese na skalu geografske širine (lijevo/desno) u visini mjerenja. 1' = 1 M (milja), 1/10' = 1 kabel.",
    pun: "Udaljenost se mjeri nautičkim šestarom: šestarom obuhvatiš razmak između točaka i preneseš ga na skalu geografske širine (lijeva ili desna strana karte) u 'visini' mjerene udaljenosti. Očitaš broj minuta (1' = 1 M = milja) i desetinki minute (1/10' = 1 kabel). Udaljenost se mjeri u nautičkim miljama i kablovima." },
  { kat: "nav", p: "Što na nautičkoj karti predstavlja oznaka + ?",
    kratko: "Hrid ili greben na nepoznatoj dubini — opasnost za plovidbu.",
    pun: "Oznaka (simbol) + predstavlja hrid ili greben na nepoznatoj dubini – opasnost za plovidbu u blizini oznake ili na samoj znaci." },
  { kat: "nav", p: "Zadane su koordinate pozicije (φ i λ) — kako pronaći poziciju na karti?",
    kratko: "Pronađeš φ i λ na skalama, nautičkim trokutima preneseš paralelu (φ) do meridijana (λ). Sjecište = pozicija.",
    pun: "Koordinate najprije pronađeš na skali geografske širine i dužine. Pomoću nautičkih trokuta liniju (paralelu) geografske širine φ preneseš do linije (meridijana) geografske dužine λ. Sjecište prenesenih linija predstavlja poziciju zadanih koordinata." },
  { kat: "nav", p: "Što je kompasna ruža (ruža vjetrova) i čemu služi?",
    kratko: "Ljubičasta kružnica numerirana 0–360°. 0°=N, 90°=E, 180°=S, 270°=W. Služi kao kutomjer za kursove i azimute.",
    pun: "Svaka karta ima najmanje jednu kompasnu ružu — ljubičastu kružnicu s ucrtanim centrom, numeriranu od 0 do 360°. 0° je na sjeveru, 90° na istoku, 180° na jugu, 270° na zapadu. Služi (uz nautičke trokute) kao kutomjer za određivanje kursova i azimuta." },
  { kat: "nav", p: "Kako pročitati karakteristiku svjetionika, npr. B Bl(3)10s12m6M?",
    kratko: "B=bijeli, Bl(3)=bljesak tri u grupi, 10s=period, 12m=visina fokusa, 6M=domet/vidljivost.",
    pun: "Simbol pomorskog svjetla ima crnu zvjezdicu i ljubičastu 'kapljicu'. Karakteristika B Bl(3)10s12m6M čita se: bijeli bljesak, tri u grupi, u periodu od 10s, na visini fokusa svjetla 12m, dometa (vidljivosti) 6M." },
  { kat: "nav", p: "Kako očitati kurs na ruži vjetrova pomoću nautičkih trokuta?",
    kratko: "Jedan trokut hipotenuzom na liniju kursa, drugi uz katetu prvog; prvi prenosiš niz hipotenuzu drugog do centra ruže. Očitaš kut u smjeru strelice.",
    pun: "Jedan trokut postaviš hipotenuzom na liniju kursa, drugi hipotenuzom na katetu prvog. Učvrstiš drugi, a prvi prenosiš niz hipotenuzu drugog dok hipotenuzom prvog ne dođeš do centra ruže. Tako paralelno preneseš smjer u centar i hipotenuzom presiječeš kružnicu ruže gdje očitaš kut. Budući da siječe kroz dvije točke, točan smjer je onaj u kojem je strelica smjera." },
  { kat: "nav", p: "Kako odrediti kurs između dvije točke pomoću trokuta na meridijanu?",
    kratko: "Trokut hipotenuzom na liniju kursa → drugim trokutom prenese do meridijana → 0 na meridijan → očitaš kut (od dva, prema strelici, razlika 180°).",
    pun: "Nautički trokut postaviš hipotenuzom na liniju kursa. Drugim trokutom preneseš liniju do najbližeg meridijana. Trokuti su i kutomjeri: preneseni smjer postaviš s 0 na liniju meridijana koji siječe polukružnicu kutova na trokutu. Očitaš jedan od dva upisana kuta (razlika 180°) ovisno o smjeru strelice." },
  { kat: "nav", p: "Kako se označava geografska širina i dužina i kako se očitavaju koordinate?",
    kratko: "φ (fi) = geografska širina, λ (lambda) = geografska dužina. Očitavaju se šestarom u odnosu na najbližu paralelu/meridijan, pa na skalu.",
    pun: "φ (fi) – geografska širina, λ (lambda) – geografska dužina. Jedan krak šestara na poziciju, drugim tražiš najkraći razmak do najbliže paralele; razmak preneseš po referentnoj paraleli na skalu geografske širine i očitaš φ u stupnjevima, minutama i desetinama minute. Isti postupak za λ uz najbliži meridijan i skalu geografske dužine." },
  { kat: "nav", p: "Kojim simbolima se označavaju podmorski kablovi i cjevovodi?",
    kratko: "Kabel = ljubičasta valovita linija. Cjevovod = linija točka-crtica (ljubičasta = cjevovod, crna = cjevovod-ispust).",
    pun: "Podmorski kabel: ljubičasta valovita linija koja spaja dvije obale. Podmorski cjevovod: linija točka-crtica koja spaja dvije obale — ljubičasta je cjevovod, crna je cjevovod-ispust." },
  { kat: "nav", p: "Zašto je Merkatorova karta karta rastuće geografske širine?",
    kratko: "Cilindrična projekcija; paralele se udaljavaju prema polovima. Zato je skala geografske širine ujedno mjerilo za udaljenost u toj visini.",
    pun: "Merkatorova (navigacijska) karta je slika dijela Zemlje u ravnini, cilindrična projekcija. Paralele su horizontalne linije koje se međusobno udaljavaju kako se približavamo polovima. Zbog toga se naziva kartom rastućih širina, a skala geografske širine ujedno je i mjerilo za udaljenost u visini mjerene udaljenosti." },
  { kat: "nav", p: "Što znači plavo obojeno more uz obalu na karti?",
    kratko: "Plavo = dubine 20 do 0 m. Svjetlije plavo 20–10 m, tamnije plavo 10–0 m.",
    pun: "Plave površine predstavljaju dubine od 20 m do 0 m. Svjetlija nijansa = 20 do 10 m, tamnija nijansa = 10 do 0 m." },
  { kat: "nav", p: "Što znači plus/križić ucrtan na kopnu?",
    kratko: "Zvonik ili crkva (često uz kraticu Zv) — objekt za orijentaciju uz obalu.",
    pun: "Simbol plusa (malteškog križa) na kopnu, uz koji može stajati kratica Zv, predstavlja zvonik ili crkvu – objekt za orijentaciju dok plovimo uz obalu." },
  { kat: "nav", p: "Što znače slova P, K, T, Kor, Š, M, Šk na morskom dijelu karte?",
    kratko: "Vrsta dna: M-mulj, P-pijesak, K-kamen, T-trava, Š-šljunak, Šk-školjke, Kor-koralji.",
    pun: "Slova označavaju vrstu morskog dna (bitno za sidrenje): M – mulj, P – pijesak, K – kamen, T – trava, Š – šljunak, Šk – školjke, Kor – koralji." },
  { kat: "nav", p: "Što je kabel i koliko iznosi?",
    kratko: "Kabel = 1/10 nautičke milje = 185 m = 1/10' geografske širine.",
    pun: "Kabel je deseti dio nautičke milje (185 m). Očitava se na skali geografske širine u visini pozicije i čini razmak od 1/10' minute geografske širine (lučnih 6'')." },
  { kat: "nav", p: "Je li kabel 1/10 ili 2/10 od 1 minute na skali geografske širine?",
    kratko: "Kabel je 1/10' geografske širine.",
    pun: "Kabel je 1/10' (jedna desetina minute) geografske širine." },
  { kat: "nav", p: "Što su Peljar, Popis svjetala i Oglasi za pomorce?",
    kratko: "Peljar i Popis svjetala = obavezni priručnici (na većim brodicama/jahtama). Oglasi za pomorce = mjesečni bilten s ispravkama.",
    pun: "Peljar i Popis svjetala i signala za maglu obavezni su priručnici na određenim gabaritima brodica i jahti. Oglasi za pomorce su mjesečni bilten kojim se objavljuju ispravke karata, peljara i popisa svjetala." },
  { kat: "nav", p: "Što je kurs?",
    kratko: "Kut između sjevernog (N) smjera meridijana i smjera plovidbe brodice.",
    pun: "Kurs (K) je kut između sjevernog smjera meridijana (N) i smjera plovidbe brodice." },
  { kat: "nav", p: "Što je azimut?",
    kratko: "Kut između N smjera meridijana i smjera prema odabranom objektu.",
    pun: "Azimut (ω) je kut između sjevernog smjera meridijana (N) i smjera prema odabranom objektu." },
  { kat: "nav", p: "Kurs K = 180° — u kojem se smjeru plovi?",
    kratko: "Prema jugu (S).",
    pun: "Kurs se prenosi nautičkim trokutima iz kompasne ruže paralelno na poziciju. Kurs od 180° je kurs prema jugu (S)." },
  { kat: "nav", p: "Što je valovita linija na karti i što se ne smije u tom području?",
    kratko: "Podmorski kabel. 150 m lijevo i desno: ne smije se zaustavljati, ribariti, sidriti, roniti.",
    pun: "Valovita ljubičasta linija na morskom dijelu karte je simbol podmorskog kabela. 150 m lijevo i desno brodovi se ne smiju zaustavljati, ribariti, sidriti ili roniti." },
  { kat: "nav", p: "Koliko iznosi 1 nautička milja i 1/10 M?",
    kratko: "1 M = 1852 m. 1/10 M (kabel) = 185 m.",
    pun: "1 nautička milja (1 M) ima 1852 m, a kabel je 1/10 milje i iznosi 185 m." },
  { kat: "nav", p: "Što znače brojevi upisani na morskom dijelu karte?",
    kratko: "Dubine u metrima (mjerene za srednje razine nižih niskih voda — maksimalne oseke).",
    pun: "Brojevi predstavljaju dubine u metrima mjerene za vrijeme srednje razine nižih niskih voda (maksimalne oseke). Gdje su dubine manje od 20 m, mogu biti izražene u metrima i decimetrima." },
  { kat: "nav", p: "Što znači ucrtano sidro na karti?",
    kratko: "Područje gdje je preporučeno sidrenje.",
    pun: "Simbol sidra znači područje gdje je preporučeno sidrenje." },
  { kat: "nav", p: "S koje strane se može obići oznaka usamljene opasnosti?",
    kratko: "S bilo koje strane (IALA sustav, dnevna oznaka).",
    pun: "Oznaka usamljene opasnosti spada u dnevne oznake (IALA sustav) i može se zaobići s bilo koje strane." },
  { kat: "nav", p: "Bočne (lateralne) oznake — kako se obilaze crvena i zelena?",
    kratko: "Pri ULAZU: lijeva strana = crvena (valjak), desna strana = zelena (stožac). Crvenu ostaviš lijevo, zelenu desno.",
    pun: "Bočne (lateralne) oznake označavaju lijevu i desnu stranu plovnog puta/kanala. Pri ulazu: lijeva strana = crvena oznaka (plutača oblik valjka), desna strana = zelena oznaka (plutača oblik stošca). Noću i za slabe vidljivosti svijetle crvenom ili zelenom karakteristikom." },
  { kat: "nav", p: "Kako odrediti kurs od točke A prema B i obrnuto?",
    kratko: "Trokutima preneseš liniju kursa u centar ruže, očitaš kut prema strelici. Obrnuti smjer = suprotno sjecište ili ±180°.",
    pun: "Razmak obuhvatiš šestarom i preneseš na skalu geografske širine. Kurs očitaš trokutima: prvi hipotenuzom na liniju kursa, prenosiš ga preko drugog do centra ruže i očitaš kut u smjeru strelice. Obrnuti smjer očitaš na suprotnom sjecištu ili tako da očitanom kursu dodaš/oduzmeš 180°." },
  { kat: "nav", p: "Kada biste koristili radar na brodici?",
    kratko: "U slabu vidljivost i noću — za detekciju obala/brodova te mjerenje udaljenosti i azimuta.",
    pun: "Radar detektira objekte (obala, drugi brodovi) u dometu elektromagnetskih valova iz rotirajuće antene; mjeri udaljenost i smjer (azimut). Posebno je koristan u uvjetima slabe vidljivosti i noću." },
  { kat: "nav", p: "Što ćete napraviti kada ugledate kardinalnu oznaku (N, E, S, W)?",
    kratko: "Držati se na strani koju oznaka pokazuje (npr. N oznaka → ostani sjeverno od nje). Označava siguran kvadrant.",
    pun: "Kardinalne oznake označavaju siguran kvadrant u odnosu na opasnost. Npr. kod N kardinalne oznake moraš se držati sjeverno od oznake (analogno za E, S, W)." },
  { kat: "nav", p: "Što označavaju posebne oznake (žute boje)?",
    kratko: "Posebna područja/objekte (oceanografske stanice, kablovi, zaštićena područja). Žute, na vrhu X, noću žuto svjetlo.",
    pun: "Posebne oznake označavaju posebna područja ili objekte (oceanografske stanice, oznake kablova i cjevovoda, zaštićena područja). Žute su boje, na vrhu imaju simbol X, a noću mogu svijetliti žutom karakteristikom." },
  { kat: "nav", p: "Koja je razlika između magnetskog kompasa i žirokompasa?",
    kratko: "Magnetski: magnetna igla pokazuje magnetne polove (nije sasvim pouzdan – varijacija). Žirokompas: žiroskop zadržava os vrtnje, postavlja se sjever-jug, pokazuje pravi sjever.",
    pun: "Magnetski kompas: lagani magnet (igla) slobodno se okreće i postavlja u smjer magnetnih silnica Zemlje. Nije sasvim pouzdan jer se odnos zemljopisnih i magnetnih meridijana (varijacija) mijenja. Žirokompas: zahvaljujući žiroskopu koji se vrti velikom brzinom trajno zadržava smjer osi vrtnje i uvijek se postavlja sjever-jug, pokazujući pravi sjever. Zvrk (kompas matica) smješten je u dnu broda, pogonjen elektromotorom." },
  { kat: "nav", p: "Što je magnetska varijacija i kako se koristi?",
    kratko: "Kut između pravog i magnetskog meridijana. Jadran ~+2,5° do +4° (2019). + = otklon na istok (E), − = na zapad (W). Upisana u ruži, preračunava se za tekuću godinu.",
    pun: "Varijacija (magnetska deklinacija) je kutna razlika između 'pravog' i 'magnetskog' meridijana. Mijenja se s vremenom; za Jadran 2019. iznosila je +2,5° do +4°. + znači otklon igle prema istoku (E), − prema zapadu (W). Podatak je upisan u kompasnoj ruži i preračunava se za tekuću godinu." },
  { kat: "nav", p: "Čemu služi priručnik Peljar?",
    kratko: "Vodič kroz područje plovidbe: luke, zaljevi, tjesnaci, sidrišta, meteo uvjeti, struje, propisi, signali.",
    pun: "Peljar daje informacije o području plovidbe: o lukama, zaljevima, tjesnacima, kanalima i sidrištima, meteorološkim uvjetima, morskim strujama te propisima za plovidbu, signalima za sigurnost itd. Ima ulogu vodiča." },
  { kat: "nav", p: "Što je dubinomjer i kako radi?",
    kratko: "Mjeri dubinu ultrazvučnim impulsima (30–50 kHz) mjereći vrijeme povratka jeke. Dijelovi: oscilator, pojačalo, indikator.",
    pun: "Dubinomjer mjeri dubinu ispod dna broda emitiranjem ultrazvučnih impulsa (30–50 kHz) i mjerenjem vremena do povratka jeke. Sastoji se od oscilatora, pojačala i indikatora (displeja). Pogreške: dvostruka/višestruka jeka kod malih dubina (regulira se pojačalom ili smještajem sondi u zatvorena kućišta s vodom i glikolom)." },

  // ===================== 2) MOTORISTIKA =====================
  { kat: "mot", p: "Gdje na brodici mora biti smješten akumulator?",
    kratko: "Suho, prozračno mjesto, udaljen od izvora topline, dobro učvršćen (u kutiji koja sprječava isticanje elektrolita).",
    pun: "Akumulator se smješta na suhim, prozračnim mjestima, udaljen od izvora topline i dobro učvršćen (u kutiji koja sprječava isticanje elektrolita)." },
  { kat: "mot", p: "Koje protupožarne mjere se moraju poduzeti na brodici?",
    kratko: "Propisana PP oprema (aparat, sjekira, kablić, deka). Izbjegavati otvoreni plamen, kontrolirati curenje goriva, ventilirati strojarnicu, držati sredstva nadohvat ruke.",
    pun: "Brodica mora imati propisanu PP opremu – prijenosni aparat, protupožarnu sjekiru te priručna sredstva (kablić za vodu, protupožarna deka). Treba izbjegavati otvoreni plamen, kontrolirati curenje goriva, spriječiti kontakt vrućih dijelova motora sa zapaljivim materijalima, ventilirati strojarnicu. Sredstva trebaju biti nadohvat ruke." },
  { kat: "mot", p: "Što sve brodica mora imati za zaštitu od požara?",
    kratko: "Aparat za gašenje + protupožarna sjekira, te priručno: kablić za vodu i protupožarna deka.",
    pun: "Oprema za gašenje požara: prijenosni protupožarni aparat(i) i protupožarna sjekira, te priručna oprema: kablić za vodu i protupožarna deka." },
  { kat: "mot", p: "Kako biste gasili požar na brodskom motoru?",
    kratko: "Aparatom punjenim pjenom, prahom ili CO2 (požar zapaljivih tekućina/para).",
    pun: "Požar para zapaljivih tekućina (gorivo/mazivo) gase se prijenosnim aparatima punjenim pjenom, prahom ili CO2 (ugljičnim dioksidom) u zatvorenim prostorima." },
  { kat: "mot", p: "Koji sustavi hlađenja motora postoje i koji je bolji?",
    kratko: "Otvoreni i zatvoreni. Zatvoreni je bolji (ekološki) — rashladna tekućina ne može lako u more u slučaju kvara.",
    pun: "Dva sustava vodenog hlađenja: otvoreni i zatvoreni. Zatvoreni je ekološki prihvatljiviji jer tekućina koja hladi motor u slučaju kvara ne može jednostavno dospjeti u more kroz ispušni sustav." },
  { kat: "mot", p: "Kako se obavlja punjenje goriva (benzin) — mjere sigurnosti?",
    kratko: "Privezati, ugasiti motor i sva trošila, iskrcati putnike, uzemljenje/naslon pištolja na metalni rub, pripremiti aparat i krpe, provjetriti, krcati polako.",
    pun: "Pristati i privezati brodicu, ugasiti motor i sva električna trošila, iskrcati putnike, spojiti uzemljenje (ili pištolj nasloniti na metalni rub otvora rezervoara – protiv statičkog elektriciteta), pripremiti aparat za gašenje, provjetriti motor, otvoriti odušak tanka, krcati polako i pripremiti krpe za upijanje. Rezervoar mora biti ispravan, gorivo ne smije curiti, ne smije biti izložen suncu, nema plamena/iskrenja u blizini." },
  { kat: "mot", p: "Od čega akumulator i instalacije moraju biti zaštićeni?",
    kratko: "Akumulator od zagrijavanja (udaljen od motora, prozračno, učvršćen). Instalacije od zagrijavanja, korozije i labavih spojeva (vibracije).",
    pun: "Akumulator mora biti zaštićen od zagrijavanja (udaljen od motora), u prozračnom prostoru, dobro pričvršćen. Ostale instalacije (kablovi, uređaji) moraju biti zaštićene od zagrijavanja i korozije te čvrsto pričvršćene da zbog vibracija ne dođe do labavih spojeva i zagrijavanja vodiča." },
  { kat: "mot", p: "Čime se podmazuje motor — razlika dvotaktni/četverotaktni?",
    kratko: "Četverotaktni: uljem iz spremnika (karter). Dvotaktni: uljem dodanim u gorivo (1–4%).",
    pun: "Četverotaktni motori podmazuju se uljem iz posebnog spremnika (karter). Dvotaktni se podmazuju uljem koje se dodaje u gorivo (benzin) u količini 1–4% (propisuje proizvođač)." },
  { kat: "mot", p: "Koji je radni takt kod četverotaktnog, a koji kod dvotaktnog motora?",
    kratko: "Četverotaktni: 3. takt (ekspanzija). Dvotaktni: 2. takt (ekspanzija + ispuh).",
    pun: "Radni takt četverotaktnog motora je 3. takt (ekspanzija), a kod dvotaktnog je 2. takt (istovremeno ekspanzija i ispuh)." },
  { kat: "mot", p: "Što učiniti ako se ulje prolije po brodu?",
    kratko: "Spriječiti istjecanje u more, upiti krpama/sorbentima. U more: zadržati mrlju, javiti lučkoj kapetaniji. Iskorišteno odložiti u namjenski spremnik na obali.",
    pun: "Spriječiti istjecanje u more, upiti ulje sredstvima za upijanje (krpe/sorbenti). Ako dospije u more: spriječiti širenje mrlje i zadržati je uz brodicu (priručno i plutajućim konopom), razgraditi deterdžentima. Kod većeg zagađenja odmah obavijestiti lučku kapetaniju. Iskorištena sredstva odložiti u namjenski spremnik i potom u za to predviđene spremnike na obali." },
  { kat: "mot", p: "Razlika otvorenog i zatvorenog sustava hlađenja?",
    kratko: "Otvoreni: morska voda kroz stjenku motora pa van kroz auspuh (rizik ulja u more). Zatvoreni: zatvoreni krug hladi motor, otvoreni hladi zatvoreni — manji rizik zagađenja.",
    pun: "Otvoreni: pumpa tjera morsku vodu kroz stjenku motora, odvodi toplinu, ulazi u ispušni sustav i izlazi kroz auspuh u more (rizik da ulje iz motora dospije u more). Zatvoreni: dva sustava – zatvoreni prolazi kroz stjenku motora, a otvoreni hladi zatvoreni. Tako je rizik zagađenja sveden na minimum." },
  { kat: "mot", p: "Tko smije biti na brodu prilikom punjenja goriva?",
    kratko: "Samo voditelj brodice i eventualno član posade. Putnici moraju biti iskrcani.",
    pun: "Prilikom punjenja gorivom na brodici treba biti samo voditelj brodice i eventualno član posade, dok putnici moraju biti iskrcani do završetka ukrcaja goriva." },
  { kat: "mot", p: "Kako se gasi požar ako nema aparata na brodu?",
    kratko: "Priručno: kablić vode te mokra deka/platno (prekrivanjem — gušenje dovoda kisika).",
    pun: "Bez aparata koriste se priručna sredstva: kablić za vodu te mokra deka ili platno za gašenje prekrivanjem." },
  { kat: "mot", p: "Što provjeriti kad se upali alarm za pregrijavanje motora?",
    kratko: "Postupno smanjiti okretaje na minimum pa ugasiti. Vjerojatni uzrok: kvar hlađenja ili podmazivanja — pregledati i popraviti.",
    pun: "Postupno smanjiti broj okretaja na minimum, pa ugasiti motor. Vjerojatni uzrok je greška sustava za hlađenje ili podmazivanje – te sustave treba pregledati i otkloniti nedostatke." },
  { kat: "mot", p: "Što sadrži instrument ploča motora?",
    kratko: "Pokazivače: struja (volt/ampermetar), gorivo, tlak ulja, temp. rashladne tekućine; dodatno okretaji i sati rada.",
    pun: "Pokazivače rada sustava: struja (voltmetar/ampermetar), gorivo (količina), ulje (tlak ulja), rashladna tekućina (temperatura). Dodatno može imati pokazivač broja okretaja i sati rada motora." },
  { kat: "mot", p: "Što treba učiniti prije paljenja motora?",
    kratko: "Provjeriti: punjenje struje/akumulator, dovoljno goriva, rashladnu tekućinu i prohodnost ulaza morske vode, razinu ulja.",
    pun: "Provjeriti rade li svi sustavi: dobiva/proizvodi li motor struju (punjenje akumulatora), ima li dovoljno goriva, je li sustav hlađenja napunjen i nema li zapreka za ulaz morske vode preko pumpe, te ima li dovoljno ulja za podmazivanje." },
  { kat: "mot", p: "Tri podjele motora s unutrašnjim izgaranjem?",
    kratko: "Po taktovima (dvotaktni/četverotaktni), po gorivu (diesel/benzinski), po montaži (vanbrodski, ugrađeni, Z-motori, jet).",
    pun: "Po broju radnih ciklusa: dvotaktni i četverotaktni; po vrsti goriva: diesel i benzinski; po načinu/mjestu montaže: vanbrodski, ugrađeni, Z-motori te jet (vodomlazni) motori." },
  { kat: "mot", p: "Ako se motor dimi ili zapali — što napraviti?",
    kratko: "Zaustaviti motor, zatvoriti dovod goriva, gasiti aparatom (pjena/prah/CO2) ili dekom. Pozvati pomoć (kanal 16 – PAN PAN, tel. 195/112).",
    pun: "Zaustaviti motor, zatvoriti dovod goriva, započeti gašenje aparatima (pjena za tekućine, prah/CO2 za masnoće/plastiku) ili prekrivanjem mokrom dekom/plahtom. Pozvati pomoć radiotelefonom (kanal 16 – PAN PAN) ili telefonom (195/112)." },
  { kat: "mot", p: "Kako gasiti požar mokrim platnom?",
    kratko: "Potpuno prekriti zapaljenu površinu → spriječi dotok kisika → gušenje.",
    pun: "Namočenim platnom potpuno se prekrije zapaljena površina i tako spriječi dotok kisika; smanjenjem kisika požar se gasi." },
  { kat: "mot", p: "Vrste motora na brodicama?",
    kratko: "Toplinski motori s unutrašnjim izgaranjem. Podjele: četverotaktni/dvotaktni; diesel/benzinski; vanbrodski/ugrađeni/Z-motori/jet.",
    pun: "Koriste se toplinski motori s unutrašnjim izgaranjem (kemijsku energiju goriva pretvaraju u mehaničku). Po broju taktova: četverotaktni, dvotaktni. Po gorivu: diesel, benzinski. Po montaži: vanbrodski, ugrađeni, Z-motori, vodomlazni (jet)." },
  { kat: "mot", p: "Čemu služi vatrogasna sjekira?",
    kratko: "Brzo sječe konope/užad koji ometaju gašenje ili zadržavaju opožarenu brodicu; otvara prostore i oslobađa osobe.",
    pun: "Služi za brzo sječenje priveznih konopa i užadi koja ometa pristup gašenju ili sprječava odvajanje opožarene brodice. Njome se otvaraju prostori kojima se pristupa požaru ili oslobađaju osobe iz zatvorenih prostora." },
  { kat: "mot", p: "Kako se hladi ulje u brodskom motoru?",
    kratko: "Otvorenim ili zatvorenim sustavom vodenog hlađenja.",
    pun: "Ulje u brodskom motoru hladi se otvorenim ili zatvorenim sustavom vodenog hlađenja." },
  { kat: "mot", p: "Kakvih akumulatora ima na brodici?",
    kratko: "Pretvaraju kemijsku u el. energiju (galvanski članak: 2 elektrode + elektrolit). Po elektrodama: olovni, Ni-Cd…; po elektrolitu: H2SO4, gel. Daju 12 V ili 24 V istosmjerno.",
    pun: "Akumulatori pohranjuju el. energiju (galvanski članak: 2 elektrode + elektrolit). Motor preko dinama puni akumulator (kontrola ampermetrom/voltmetrom). Vrste po elektrodama: olovni, srebrni, čelični, Ni-Cd, Ni-Fe, Ni-Mh; po elektrolitu: razrijeđena sumporna kiselina (H2SO4), gel (silica gel, ne cure, otporni). Daju istosmjernu struju 12 V ili 24 V." },
  { kat: "mot", p: "Kako se podmazuje benzinski četverotaktni, a kako dvotaktni motor?",
    kratko: "Četverotaktni: ulje iz kartera (filter, pumpa). Dvotaktni: ulje u gorivu 1–4% (u rezervoar ili dozirano u karburator).",
    pun: "Četverotaktni: ulje iz spremnika (karter), uz filter i pumpu ulja. Dvotaktni: ulje dodano gorivu 1–4%, izravno u rezervoar ili dozirano u karburator iz posebnog spremnika." },
  { kat: "mot", p: "Čemu služi motorno ulje?",
    kratko: "Smanjuje trenje, štiti klizne površine, odvodi toplinu.",
    pun: "Motorno ulje služi za smanjenje trenja u motoru, zaštitu kliznih površina i odvođenje topline." },
  { kat: "mot", p: "Koju opremu za sprječavanje onečišćenja trebamo imati?",
    kratko: "Posuda/vrećica za kruti otpad (sve brodice); posuda za otpadno ulje i sredstva za upijanje zauljenih ostataka (brodice s ugrađenim motorom).",
    pun: "Pravilnik propisuje: posudu/vrećicu za kruti otpad (sve brodice), posudu za otpadno ulje (brodice s ugrađenim porivnim uređajem) i sredstva za upijanje i odvajanje zauljenih ostataka (brodice s ugrađenim porivnim uređajem)." },
  { kat: "mot", p: "Što je MARPOL konvencija?",
    kratko: "Međ. konvencija o zaštiti mora od onečišćenja (MARPOL 73/78). Jadran = posebno područje: zabranjeno ispuštanje ulja/goriva i krutog otpada (osim razgradive hrane bez masnoća). Onečišćenje javiti kapetaniji.",
    pun: "Međunarodna konvencija o zaštiti mora od onečišćenja uljima i otpadnim tvarima (MARPOL 73/78), potpisnica je i RH. Jadran je posebno područje gdje je zabranjeno ispuštanje ulja, goriva te krutog otpada (plastika, guma, najlon, staklo), osim otpadaka hrane u razgradivom stanju bez masnoća. Voditelj brodice dužan je svako uočeno onečišćenje prijaviti lučkoj kapetaniji." },

  // ===================== 3) POMORSTVO, PROPISI, METEOROLOGIJA =====================
  { kat: "pom", p: "Nabroji osnovne dijelove konstrukcije brodice?",
    kratko: "Pramac, krma (zaobljena/zrcalo), kobilica, pramčana i krmena statva, rebra, trenica (bočna obloga), razma (valica), pramica (škaf), nadgrađe.",
    pun: "Glavni dijelovi: pramac, krma (zaobljena ili ravna – zrcalo), kobilica, pramčana statva, krmena statva, rebra, trenica (bočna obloga), razma (valica), pramica (škaf), nadgrađe (dio iznad palube – kabina)." },
  { kat: "pom", p: "Što je kobilica?",
    kratko: "Najniža uzdužna veza broda, ključ uzdužne čvrstoće; ide od krme do pramca u simetrali, prelazi u statve.",
    pun: "Kobilica je najniža uzdužna veza broda i jedan od najvažnijih elemenata uzdužne čvrstoće. Prostire se uzduž cijele dužine broda od krme do pramca u simetrali; u pramcu prelazi u pramčanu, a na krmi u krmenu statvu." },
  { kat: "pom", p: "Što je gaz, a što nadvođe?",
    kratko: "Gaz = dubina urona (do najniže točke). Nadvođe = visina boka od vodene linije do ruba glavne palube. Ukrcaj tereta: gaz raste, nadvođe pada.",
    pun: "Gaz je dubina do koje je plovilo uronjeno (razmak od vodene linije do najniže točke podvodnog dijela). Nadvođe je visina boka od vodene linije do gornjeg ruba glavne (nepropusne) palube. Pri ukrcaju tereta gaz se povećava, a nadvođe smanjuje." },
  { kat: "pom", p: "Koji dijelovi brodice se nalaze iznad palube?",
    kratko: "Nadgrađe, kabina, jarbol itd.",
    pun: "Paluba je stalni pokrov trupa (glavna radna površina, ojačava trup). Iznad palube može se dodati nadgrađe, kabina, jarbol itd." },
  { kat: "pom", p: "Tko je nadležan za red u lukama?",
    kratko: "Lučka kapetanija (plovidba, privez, sidrenje, ukrcaj/iskrcaj, kupališta, čistoća mora itd.).",
    pun: "Nadzor nad redom u lukama obavlja lučka kapetanija: plovidba, pristajanje, privezivanje, odvezivanje, sidrenje, ukrcaj/iskrcaj tereta i putnika, red na kupalištima, kupanje, ronjenje, sportske aktivnosti, čistoća mora i obala te sprječavanje onečišćenja." },
  { kat: "pom", p: "Definicija brodice i jahte?",
    kratko: "Brodica: 2,5–15 m, motor >5 kW, <15 BT, <12 putnika. Jahta: >15 m, do 12 putnika, za sport/razonodu i dulji boravak.",
    pun: "Brodica je plovni objekt za plovidbu morem dužine 2,5–15 m, snage porivnih strojeva veće od 5 kW, manje od 15 BT, prevozi manje od 12 putnika. Jahta je plovni objekt za sport i razonodu dužine veće od 15 m, uz posadu prevozi do 12 putnika, namijenjena duljem boravku na moru." },
  { kat: "pom", p: "Kako rasporediti teret zbog stabiliteta?",
    kratko: "Ravnomjerno; teže težine što niže (bliže dnu). Voditelj odgovoran za stabilitet pri ukrcaju i tijekom plovidbe (sile valova/vjetra).",
    pun: "Voditelj je odgovoran za stabilitet pri ukrcaju i razmještaju osoba, tereta, goriva, vode i opreme te tijekom plovidbe (dinamičke sile valova i vjetra). Sve treba ravnomjerno rasporediti, a veće težine smjestiti blizu dna brodice." },
  { kat: "pom", p: "Što je stabilitet i kada je brodica indiferentnog stabiliteta?",
    kratko: "Stabilitet = sposobnost vraćanja u uspravan položaj. Metacentar iznad težišta = stabilna; ispod = labilna (prevrće se); u težištu = indiferentna (ostaje nagnuta).",
    pun: "Stabilitet je osobina da se brodica iz nagnutog položaja sama vrati u uspravan kad prestane sila koja ju je nagnula. Metacentar je točka u kojoj okomica iz hvatišta uzgona siječe uzdužnicu; udaljenost do težišta je metacentarska visina. Metacentar iznad težišta = stabilna ravnoteža; ispod = labilna (prevrće se); u težištu = indiferentna (ostaje u tom položaju). Stabilitet se povećava spuštanjem težišta (teški predmeti niže)." },
  { kat: "pom", p: "Gdje se registriraju brodice, a gdje jahte?",
    kratko: "Brodice → Očevidnik brodica. Jahte → Očevidnik jahti.",
    pun: "Brodice se upisuju u Očevidnik brodica, a jahte u Očevidnik jahti." },
  { kat: "pom", p: "Što sadrži dozvola za plovidbu i koja su područja plovidbe?",
    kratko: "Podatke o brodici/vlasniku/motoru/posadi, opremu, područje plovidbe. Područja: I (sva mora), II (Jadran), III (unutarnje/teritorijalno more), IV (luke, zaljevi, rijeke).",
    pun: "Dozvola sadrži: tijelo izdavatelja, broj, datum/mjesto, ime i oznaku brodice, namjenu, podatke o vlasniku, brodici (tip, dužina, BT, broj putnika, godina, materijal), motoru, posadi, rok valjanosti, opremu i područje plovidbe. Područja: I – sva mora (Ia do 20 M od obale); II – Jadran (IIa do 12 M); III – unutarnje i teritorijalno more RH (IIIa do 6 M, IIIb do 3 M, IIIc do 1 M); IV – luke, zaljevi, rijeke Jadranskog slijeva i Prokljansko jezero." },
  { kat: "pom", p: "Gdje je dozvoljeno glisirati?",
    kratko: "Više od 300 m od obale ili od ograđenog kupališta.",
    pun: "Glisiranje je dozvoljeno više od 300 m od obale ili od ograđenog prostora kupališta." },
  { kat: "pom", p: "Na kojoj udaljenosti od obale smijemo ploviti (brzine)?",
    kratko: "Vesla <50 m; motor/jedrilice >50 m (i >150 m od neograđenog kupališta). 0–150 m: max 5 čv; 150–300 m: max 8 čv; gliseri >300 m.",
    pun: "Vesla: manje od 50 m od obale. Motorne brodice i jedrilice: više od 50 m od obale i od ograđenog kupališta, te više od 150 m od neograđenog kupališta. Do 150 m od obale svi plove s posebnom pažnjom brzinom ne većom od 5 čvorova; od 150 do 300 m ne većom od 8 čvorova; gliseri koji glisiraju – više od 300 m od obale ili kupališta." },
  { kat: "pom", p: "Opiši buru (i njezine tipove i predznake)?",
    kratko: "NE vjetar, hladan i suh, mahovit (na refule), s kopna na more, nagli razvoj. Tipovi: anticiklonska (vedra) i ciklonska (tamna/škura). Predznaci: oblaci na planinama, sijevanje bez grmljavine, porast tlaka.",
    pun: "Bura (NNE-ENE) puše s kopna na more, hladna je i suha, izrazito mahovita (na udare/refule). Ljeti traje 1–3 dana, zimi do 7. Opasna zbog naglog pojavljivanja (10–15 min). Nastaje prelijevanjem hladnog zraka iz Panonske zavale preko Dinarida; najjača na prijevojima (Senj, Maslenica, Vrulja…). Tipovi: anticiklonska (vedra) – anticiklona nad srednjom Europom; ciklonska (tamna/škura) – hladni sektor ciklone, obilne padaline. Predznaci: oblaci iznad obalnih planina, sijevanje bez grmljavine, porast tlaka zraka." },
  { kat: "pom", p: "Opiši jugo i njegove predznake?",
    kratko: "SE (jugoistočni), topao i vlažan, razvija se sporo (12–24 h), razoran nakon par dana. Anticiklonalno (suho/gnjilo) i ciklonsko (kiša, grmljavina). Predznaci: porast temp., pad tlaka, mrtvo more, maglovit horizont.",
    pun: "Jugo (ESE-SSE, 'široko') – zračna masa iz S. Afrike preko Sredozemlja dolazi kao topao i vlažan zrak (prljave kiše). Razvija se 12–24 h, razornu snagu postiže nakon nekoliko dana. Anticiklonalno (suho, gnjilo jugo): vedro, raste temperatura/vlaga. Ciklonsko: kiša, grmljavina, olujne brzine. Predznaci: porast temperature i pad tlaka, porast plime/mrtvo more iz JZ, maglovit horizont, valovi iz JI smjera, izmaglica na južnom horizontu." },
  { kat: "pom", p: "Opiši maestral i predznake?",
    kratko: "NW (sjeverozapadni), ljetni, vlažan, umjeren (5–8 m/s), lijepo vrijeme. Počinje 8–9 h, najjači ~14 h, prestaje ~18 h. Predznak: sivkasto-bijeli oblaci nad kopnom.",
    pun: "Maestral (WNW-NW) – sjeverozapadni ljetni vjetar umjerene jačine (5–8 m/s) između azorskog maksimuma i niskog tlaka na istoku. Prati lijepo vrijeme i ublažuje sparinu. Počinje puhati 8–9 h, najjači oko 14 h, prestaje oko 18 h ili pri zalasku. Povoljan za jedrenje. Predznak: 1–2 h prije nad kopnom sivkasto-bijeli oblaci; može zapuhati nakon kiše." },
  { kat: "pom", p: "Koja područja (kategorije) plovidbe poznaje Pravilnik o brodicama i jahtama?",
    kratko: "I (sva mora; Ia do 20 M), II (Jadran; IIa do 12 M), III (unutarnje/teritorijalno more; IIIa 6 M, IIIb 3 M, IIIc 1 M), IV (luke, zaljevi, rijeke).",
    pun: "Područje I – međunarodna plovidba svim morima (Ia: do 20 M od obale). Područje II – međunarodna plovidba Jadranom (IIa: do 12 M). Područje III – unutarnje morske vode i teritorijalno more RH (IIIa: do 6 M, IIIb: do 3 M, IIIc: do 1 M). Područje IV – luke, zaljevi, rijeke Jadranskog slijeva i Prokljansko jezero." },
  { kat: "pom", p: "Nabroji vjetrove na Jadranu i smjerove?",
    kratko: "Bura (NE), jugo (SE), maestral (NW), oštro (S), lebić/garbin (SW), pulenat (W), tramontana (N-NW), levant (E), burin/kopnenjak i zmorac (obalna cirkulacija).",
    pun: "Najčešći: bura (NNE-ENE), jugo (ESE-SSE), maestral (WNW-NW). Ostali: oštro (S), lebić/garbin (SW), pulenat (W), tramontana (N-NW), levant (E), te vjetrovi obalne cirkulacije – burin (kopnenjak) i zmorac." },
  { kat: "pom", p: "Što je nadgrađe?",
    kratko: "Konstruktivni dio iznad razme/palube koji zatvara prostor za posadu/putnike ili opremu.",
    pun: "Nadgrađe je konstruktivni dio brodice iznad razme ili palube koji zatvara prostor za boravak posade i putnika ili za smještaj opreme." },
  { kat: "pom", p: "Što se na brodici nalazi iznad razme?",
    kratko: "Nadgrađe, kabina, jarbol, palubna kućica itd.",
    pun: "Iznad razme može se nalaziti nadgrađe, kabina, jarbol, palubna kućica itd." },
  { kat: "pom", p: "Vrste brodica obzirom na oblik trupa?",
    kratko: "Deplasmanske (zaobljen trup, ograničena brzina – guc, pasara, leut), gliserske (ravno dno, klize). Po trupovima: jedno-, dvo- (katamaran), tro- (trimaran).",
    pun: "Po obliku trupa: deplasmanske (zaobljen trup, dobre plovidbene sposobnosti, ograničena brzina – guc, pasara, leut, batana; poludeplasmanske – pilotina) i gliserske (ravno dno bez kobilice, klize po površini). Po broju trupova: jednotrupci, dvotrupci (katamarani), trotrupci (trimarani)." },
  { kat: "pom", p: "Koje namjene plovila poznaješ?",
    kratko: "Za osobne potrebe, gospodarska, javna.",
    pun: "Namjene plovila: za osobne potrebe, gospodarska, javna." },
  { kat: "pom", p: "Kakvom brodicom/jahtom smije upravljati voditelj kategorije B?",
    kratko: "Brodice za osobne potrebe do 15 BT / 15 m, do 12 putnika, motor >5 kW (neograničeno), u području IIa, III, IV. Jahte za osobne potrebe i charter bez posade do 30 BT (IIa, III, IV).",
    pun: "Kategorija B: brodice za osobne potrebe do 15 BT i 15 m, do 12 putnika, ugrađeni/vanbrodski motor >5 kW (neograničene snage) u području plovidbe IIa, III, IV; brodice koje prevoze putnike (IIIb, IIIc, IV); brodice za teret i ribarske (III, IIIa, IIIb, IIIc, IV); te jahte za osobne potrebe i one koje se iznajmljuju bez posade do 30 BT u području IIa, III, IV." },
  { kat: "pom", p: "Raspon plime i oseke na Jadranu?",
    kratko: "Naizmjenično dizanje/spuštanje mora (Mjesec+Sunce), 2× dnevno svakih 12 h 25 min. Raspon ~0,35 m (jug) do ~1,00 m (sjever).",
    pun: "Plima i oseka su naizmjenično dizanje i spuštanje razine mora pod utjecajem gravitacije Mjeseca i Sunca; izmjenjuju se dvaput dnevno svakih 12 h 25 min. Jadran je područje umjerenih mijena; najveći raspon ~1,00 m (0,35 m na jugu, 1,00 m na sjevernom Jadranu). Uz niski tlak i jako jugo može izazvati probleme i štete." },
  { kat: "pom", p: "Smjer morskih struja na Jadranu?",
    kratko: "Ulazi istočnom obalom s juga prema sjeveru, vraća se zapadnom. Brzina 0,5–1 čv (u prolazima do 4 čv). Ne ometaju plovidbu.",
    pun: "Glavna struja ulazi istočnom obalom s juga (Jonsko more) prema sjeveru i vraća se zapadnom obalom. Brzina je konstantna 0,5–1 čvor, u uskim prolazima do 4 čvora. Ne predstavljaju problem za plovidbu." },
  { kat: "pom", p: "Nabroji opremu brodice za trup (područje plovidbe III)?",
    kratko: "Sidro, sidreno uže/lanac 25–100 m, bitve, 3 užeta za privez, kablić s ispolcem, sisaljka, 2 vesla (ili pričuvni motor) i čaklja, kormilarenje u nuždi.",
    pun: "Oprema za trup (III): sidro propisane mase, sidreno uže ili lanac 25–100 m, bitve ili drugi uređaj za privez, 3 užeta za privez prikladne duljine i čvrstoće, kablić s ispolcem, sisaljka, 2 vesla s rašaljama (ili pričuvni porivni uređaj) i čaklja, kormilarenje u nuždi (rezervno/ručno)." },
  { kat: "pom", p: "Kako se mora opteretiti brodica da ostane stabilna?",
    kratko: "Ravnomjeran raspored osoba i tereta; teže težine blizu dna. Voditelj odgovoran pri ukrcaju i u plovidbi.",
    pun: "Voditelj je odgovoran za stabilitet pri ukrcaju i razmještaju osoba/tereta te tijekom plovidbe (dinamičke sile valova i vjetra). Sve treba ravnomjerno rasporediti, a veće težine smjestiti blizu dna brodice." },
  { kat: "pom", p: "Kako izgleda meteorološko izvješće (DHMZ)?",
    kratko: "Datum/vrijeme, eventualno upozorenje, stanje (položaj ciklona/anticiklona), prognoza za prvih 12 h pa daljnjih 12 h; za sjeverni, srednji i južni Jadran.",
    pun: "Izvješće DHMZ-a odnosi se na datum i vrijeme, može započeti upozorenjem. Slijedi stanje (položaj ciklona/anticiklona nad Jadranom), pa prognoza za prvih 12 sati, zatim za daljnjih 12 sati. Može se odnositi na sjeverni, srednji i južni Jadran." },
  { kat: "pom", p: "Čime upravljaju voditelj kategorije A i kategorije C?",
    kratko: "A: do 7 m, motor do 15 kW, područje IIIa-IV. C: osobne/gospodarske u I, Ia, II; putnici u III/IIIa; jahta do 30 BT u I, Ia, II.",
    pun: "Kategorija A: brodice za osobne potrebe do 7 m, motor do 15 kW, u području IIIa, IIIb, IIIc, IV; te član posade na brodicama koje prevoze putnike/teret/ribarskim u III i nižim. Kategorija C: brodica za osobne i gospodarske potrebe u I, Ia, II; prijevoz putnika u III i IIIa; jahta do 30 BT (bilo koja namjena) u I, Ia, II. Stječe se nakon 25 h teorije, 6 h prakse i položenog ispita." },
  { kat: "pom", p: "Proces upisa brodice u Očevidnik brodica?",
    kratko: "Upis kod kapetanije po prebivalištu vlasnika / pretežnom zadržavanju. Prilaže se vlasništvo, carine/porezi, osiguranje (>15 kW), naknada, CE/svjedodžba o gradnji. Pregled → oznaka + dozvola.",
    pun: "Brodica se upisuje kod lučke kapetanije/ispostave po prebivalištu vlasnika ili gdje se pretežno zadržava. Upisuju se sve osim malenih (<2,5 m i <5 kW), sportskih/veslačkih, kajaka, daski itd. Prilaže se: dokaz vlasništva brodice i motora, podmireni carinski/porezni dug, polica osiguranja (motor >15 kW), naknada, CE deklaracija ili svjedodžba o gradnji. Sposobnost se utvrđuje pregledom; brodica dobiva oznaku (dva slova + broj) i dozvolu. Pregled (osnovni, redovni, izvanredni) vrši kapetanija." },
  { kat: "pom", p: "Što je mrtvo more?",
    kratko: "Valovi koji su izašli izvan zone vjetra koji ih je stvorio / valovi nakon prestanka vjetra. Na Jadranu nakon juga; valovi niži ali do 3× duži.",
    pun: "Mrtvo more su valovi koji su uznapredovali izvan zone vjetra koji ih je stvorio, odnosno valovi nakon prestanka vjetra. Na Jadranu nastaje nakon juga (rjeđe maestrala/lebića). Prestankom vjetra visina valova se smanjuje, a dužina povećava i do tri puta." },
  { kat: "pom", p: "Što čini obalno more RH i smije li B kategorija ploviti uz Italiju?",
    kratko: "Obalno more = unutarnje morske vode + teritorijalno more (12 M od polazne crte). B može ploviti obalnim morem RH i svake države koja priznaje HR dozvolu; plovilo treba dozvolu za područje III ili niže.",
    pun: "Obalno more RH čine unutarnje morske vode (luke, zaljevi, more između crte niske vode i polazne crte) i teritorijalno more (pojas 12 M od polazne crte). Polazne crte (niska voda, ravne crte ulaza/spojeva) ucrtane su u kartu 'Jadransko more' (Hrvatski hidrografski institut). Voditelj kategorije B može ploviti obalnim morem RH i obalnim morem svake države koja priznaje HR dozvolu; plovilo mora imati dozvolu za područje plovidbe III ili niže." },

  // ===================== 4) MANEVRIRANJE, SIGURNOST, PRVA POMOĆ =====================
  { kat: "man", p: "O čemu ovisi dužina priveznih konopa?",
    kratko: "O dimenzijama plovila. Do 15 m: pramčani i krmeni = pola do cijele dužine brodice; špringovi = do dvostruke dužine tih konopa.",
    pun: "Ovisi o dimenzijama plovila. Iskustveno za brodice do 15 m: pramčani i krmeni konop dužine od pola brodice do dužine brodice, a špringovi do dvostruke dužine pramčanog/krmenog konopa." },
  { kat: "man", p: "Koja svjetla ima jedrenjak do 20 m?",
    kratko: "Bočna + krmeno (može i kružna crveno iznad zelenog). Na motor: kao motorna brodica (bočna, krmeno, jarbolno).",
    pun: "Jedrenjak do 20 m noću/slaba vidljivost ističe bočna svjetla i krmeno svjetlo; može (po želji) i kružna svjetla crveno iznad zelenog. Kada plovi na motor, ističe svjetla motorne brodice: bočna, krmeno i jarbolno." },
  { kat: "man", p: "Koja svjetla ima tegljač?",
    kratko: "Bočna, krmeno + svjetlo za tegljenje iznad njega; jarbolna: 3 u nizu (tegalj >200 m) ili 2 (tegalj <200 m).",
    pun: "Tegljač pri tegljenju ističe bočna svjetla, krmeno svjetlo i iznad njega svjetlo za tegljenje, te jarbolna svjetla: tri jedno iznad drugog kada je tegalj duži od 200 m, a dva kada je kraći od 200 m." },
  { kat: "man", p: "Koja svjetla ima tegljeni brod?",
    kratko: "Bočna i krmeno (ako može); inače mora biti osvijetljen da se vide dimenzije.",
    pun: "Tegljeno plovilo, ako je moguće, ističe bočna svjetla i krmeno svjetlo. Ako ne može, mora biti osvijetljeno tako da se u mraku vide njegove dimenzije." },
  { kat: "man", p: "Koja svjetla ima motorna brodica s kabinom do 7 m?",
    kratko: "Bočna svjetla + bijelo kružno svjetlo na jarbolu (min. 1 m iznad bočnih).",
    pun: "Motorna brodica s kabinom do 7 m ističe bočna svjetla i bijelo kružno svjetlo na jarbolu (kružno svjetlo najmanje 1 m iznad razine bočnih svjetala)." },
  { kat: "man", p: "Koja svjetla ima ribarski brod – koča?",
    kratko: "Bočna, krmeno (i jarbolno ako >50 m) + dva kružna: zeleno iznad bijelog.",
    pun: "Koča ističe bočna svjetla, krmeno svjetlo (i jarbolno ako je duža od 50 m), te dva kružna svjetla – zeleno iznad bijelog." },
  { kat: "man", p: "Koja svjetla ima usidreni brod (<50 m i >100 m)?",
    kratko: "<50 m: jedno bijelo kružno. >100 m: dva bijela kružna (pramčano više) + osvjetljena paluba.",
    pun: "Usidreni brod kraći od 50 m ističe jedno bijelo kružno svjetlo. Brod duži od 100 m ističe dva bijela kružna svjetla (pramčano na većoj visini od krmenog) te ima upaljena svjetla koja osvjetljavaju palubu." },
  { kat: "man", p: "Tko ima prednost: brodovi koji uplovljavaju ili isplovljavaju iz luke?",
    kratko: "Prednost imaju oni koji ISPLOVLJAVAJU. Brodovi <20 m sklanjaju se onima >20 m.",
    pun: "U ograničenom prostoru (luke, pristaništa) prednost imaju brodovi koji isplovljavaju u odnosu na one koji uplovljavaju. Također, brodovi kraći od 20 m sklanjaju se s puta brodovima dužim od 20 m." },
  { kat: "man", p: "Boje, položaj i kut vidljivosti svjetlosnih oznaka broda?",
    kratko: "Bočna: crveno (lijevo) i zeleno (desno) — 112,5°. Jarbolno: bijelo naprijed 225°. Krmeno: bijelo natrag 135°.",
    pun: "Bočna svjetla (na bokovima): crveno se vidi 112,5° od pramčanice ulijevo, zeleno 112,5° udesno. Jarbolno svjetlo (na jarbolu) bijelo, vidi se 225° prema naprijed. Krmeno svjetlo (na krmi) bijelo, vidi se 135° prema natrag. (112,5+112,5+135 = 360°.)" },
  { kat: "man", p: "Jedrilica i ribarica koja lovi — tko se sklanja?",
    kratko: "Jedrilica se sklanja ribarici.",
    pun: "Jedrilica se sklanja s puta ribarici koja lovi." },
  { kat: "man", p: "Ribarica lovi, s obje strane joj prilazi po jedna jedrilica — tko koga izbjegava?",
    kratko: "Obje jedrilice sklanjaju se ribarici. Međusobno: vjetar u isti bok → ona bliže vjetru izbjegava; različiti bokovi → ona s vjetrom u lijevom boku izbjegava onu s vjetrom u desnom.",
    pun: "Obje jedrilice sklanjaju se ribarici. Međusobno se izbjegavaju ovisno o smjeru vjetra: ako primaju vjetar u isti bok, jedrilica bliže vjetru izbjegava onu dalje od vjetra; ako primaju vjetar različitim bokovima, ona koja prima vjetar u lijevi bok izbjegava onu koja ga prima u desni." },
  { kat: "man", p: "Zvučni signali: skrećem desno, lijevo, vozim krmom?",
    kratko: "Desno: 1 kratki. Lijevo: 2 kratka. Krma (unatrag): 3 kratka.",
    pun: "Skrećem desno: 1 kratki (1 s). Skrećem lijevo: 2 kratka. Vozim krmom (unatrag): 3 kratka." },
  { kat: "man", p: "Koja je dnevna oznaka za usidreni brod?",
    kratko: "Crna kugla (promjer 30–60 cm, ovisno o veličini broda).",
    pun: "Dnevna oznaka za usidreni brod je crna kugla (promjer 30–60 cm, ovisno o veličini broda)." },
  { kat: "man", p: "Tko ide prije: brodica iz luke ili u luku? Veći ili manji brod?",
    kratko: "Prednost: oni koji isplovljavaju iz luke. U ograničenom prostoru prednost imaju brodovi >20 m nad onima <20 m.",
    pun: "Pri ograničenom manevriranju (luke, prolazi, kanali) prednost imaju brodovi koji isplovljavaju u odnosu na one koji uplovljavaju. Također, prednost imaju brodovi duži od 20 m u odnosu na plovila kraća od 20 m." },
  { kat: "man", p: "Brodovi su u protukursu — što činiti?",
    kratko: "Oba na vrijeme i odlučno skreću UDESNO i mimoiđu se lijevim bokovima.",
    pun: "Kad su brodovi u protukursu (ili približno), svaki treba na vrijeme i odlučno promijeniti kurs udesno i mimoići se lijevim bokom." },
  { kat: "man", p: "Kako se pretječe druga brodica?",
    kratko: "Brod koji pretječe sklanja se onome kojeg pretječe; pretjecani drži kurs i brzinu dok ne bude prestignut. Može s obje strane.",
    pun: "Brod koji pretječe sklanja se s puta brodu kojeg pretječe, a pretjecani zadržava smjer i brzinu dok ne bude prestignut. Pretjecanje se može obaviti s obje strane." },
  { kat: "man", p: "Koliko traje kratki, a koliko dugi zvučni signal?",
    kratko: "Kratki: 1 s. Dugi: 4–6 s.",
    pun: "Kratki zvučni signal traje 1 s, a dugi zvučni signal 4–6 s." },
  { kat: "man", p: "Što je četverovez?",
    kratko: "Krma privezana na obalu (2 krmena konopa), pramac prema otvorenom moru vezan za mooring/plutaču ili preko sidra.",
    pun: "Četverovez je način priveza gdje je krma privezana na obalu (s dva krmena konopa), a pramac prema otvorenom moru privezan za mooring, plutaču ili preko sidrenjaka i sidra za morsko dno." },
  { kat: "man", p: "Koje privezne konope treba imati pri bočnom vezu?",
    kratko: "Minimum: pramčani, krmeni i pramčani špring. Preporuka i krmeni špring.",
    pun: "Pri bočnom vezu treba imati minimalno: pramčani i krmeni konop te pramčani špring. Preporuča se i krmeni špring." },
  { kat: "man", p: "Koliko dug sidrenjak na dubini od 4 m?",
    kratko: "3–6× dubina → 12 do 24 m.",
    pun: "Pri sidrenju na 4 m dužina sidrenjaka treba biti 3–6 dubina, dakle 12 do 24 m." },
  { kat: "man", p: "Kako se sidri?",
    kratko: "Pramcem u vjetar, spustiti sidro, voziti unatrag/opadati otpuštajući 3–6× dubine, ukopati sidro laganom vožnjom unatrag. Ako ne drži – više sidrenjaka ili ponoviti manevar.",
    pun: "Pri dolasku osmotriš vjetar, druge brodove i dubinu. Dođeš pramcem u vjetar, zaustaviš brodicu i spustiš sidro na dno, pa voziš unatrag (ili opadaš niz vjetar) otpuštajući sidrenjak na omjer 3–6× dubine. Laganom vožnjom unatrag ukopaš sidro; kad sidrenjak je napet i brodica stoji, zaustaviš motor i okreneš pramac u vjetar/struju. Ako se sidro ne ukopa, ispustiš još sidrenjaka ili prekineš manevar, podigneš sidro i ponoviš." },
  { kat: "man", p: "Što je orepina i čemu služi?",
    kratko: "Tanji konop s plutačom vezan za vrh (krunu) sidra; označava poziciju i omogućuje izvlačenje sidra iz suprotnog smjera ako zapne (kamenito dno).",
    pun: "Pri sidrenju na kamenitom dnu, za vrh (krunu) sidra veže se tanji konop s plutačom na kraju – OREPINA. Označava poziciju sidra i omogućuje da se, ako sidro zapne za kamen, izvuče potezanjem iz suprotnog smjera." },
  { kat: "man", p: "Nabroji tipove sidra i čemu služi olujno sidro?",
    kratko: "Admiralitetsko, Hallovo, Danforth, plužno (CQR), Bruce, Mačak. Olujno (zavlačno) sidro: pri neupravljivosti, pušta se s pramca, stvara otpor i drži pramac u valove/vjetar.",
    pun: "Vrste: Admiralitetsko, Hallovo patentno, Danforth, plužno (C.Q.R.) patentno, Bruce, Mačak. Zavlačno (olujno) sidro koristi se kod otkazivanja pogona/neupravljivosti: pušta se s pramca, oblikom stvara otpor kretanju i postavlja plovilo pramcem u valove i vjetar." },
  { kat: "man", p: "Kako se bočno privezati i isploviti (desnokretni propeler)?",
    kratko: "Privez lijevim bokom: prilaz ~45°, snažno unatrag (izboj krme ulijevo prilazi krmu), hvataš pramčani špring. Isplov: napni pramčani špring, otpusti ostalo, krma se odmiče pa vozi unatrag.",
    pun: "Kod desnokretnog propelera izboj krme ulijevo olakšava pristajanje lijevim bokom. Pripremiš bokobrane i konope, priđeš ukoso ~45°, zaustaviš stroj, prilaziš inercijom pa snažno unatrag dok se brod gotovo ne zaustavi; uhvatiš pramčani špring koji zaustavlja brod i primiče pramac, a izboj propelera primiče krmu — brod legne paralelno obali. Isplov: voziš polako naprijed s kormilom ulijevo da napneš pramčani špring, otpustiš ostale konope; krma se odmiče od obale, pa prebaciš kormilo nadesno i voziš unatrag, otpustiš špring i izlaziš." },
  { kat: "man", p: "Koje sidro je najbolje za pjeskovito dno i kolika težina?",
    kratko: "Plužna sidra (CQR, Bruce, Delta). Iskustveno ~1,5 kg sidra na 1 m dužine brodice.",
    pun: "Za pjeskovito dno najbolja su plužna sidra: CQR, Bruce ili Delta. Težina ovisi o dužini: iskustvena mjera je 1,5 kg sidra na 1 m dužine brodice." },
  { kat: "man", p: "Hijerarhija izbjegavanja: ribarica koja lovi, jedrilica, motorni brod?",
    kratko: "Ribarica > jedrilica > motorni brod. Ribarica drži kurs, jedrilica izbjegava ribaricu, motorni brod izbjegava i ribaricu i jedrilicu.",
    pun: "Hijerarhija prednosti: ribarska brodica koja lovi ima prednost pred jedrilicom, a jedrilica pred motornom brodicom. Ribarica plovi svojim kursom i brzinom, jedrilica izbjegava ribaricu, a motorna brodica izbjegava i ribaricu i jedrilicu." },
  { kat: "man", p: "Čovjek u moru — kako prilaziš i što s motorom?",
    kratko: "Prilaziš smanjenom brzinom prema njemu i prema valovima/vjetru; dobaciš kolut/prsluk s plutajućim konopom. Pri podizanju UGASIŠ MOTOR (zbog propelera).",
    pun: "Čovjeku se prilazi smanjenom brzinom, prema njemu i prema valovima/vjetru. Dobaciš mu kolut ili prsluk za spašavanje za koji je vezan sigurnosni (plutajući) konop. U trenutku podizanja iz mora UGASIŠ motor, da u slučaju skliznuća/ponovnog pada čovjek ne strada od propelera." },
  { kat: "man", p: "Navedi signale opasnosti na moru?",
    kratko: "MAYDAY 3×, crvene rakete/padobranske, ručne buktinje, SOS svjetlom/zvukom, slova NC, narančasta plahta s kvadratom i krugom, dim, vatra, dizanje/spuštanje ruku, pucnjevi svake minute, neprekidni zvuk. Zrakoplovu: V (opća pomoć), X (medicinska).",
    pun: "Međunarodni signali pogibelji: izgovaranje MAYDAY triput, rakete s crvenim zvjezdicama, rakete s padobranom crvenog svjetla, ručne buktinje crvenog svjetla, SOS (Morse) svjetlom/ogledalom/zvukom, slova NC, kvadratna zastava sa znakom kugle iznad/ispod, narančasta jedrenina s crnim kvadratom i krugom, dim, zapaljena vatra, dizanje i spuštanje ruku, pucnjevi u razmacima od jedne minute, neprekinuto zvučno oglašavanje. Za zrakoplov: slovo V (opća pomoć), slovo X (medicinska pomoć)." },
  { kat: "man", p: "Kako izgleda prsluk za spašavanje i što omogućava?",
    kratko: "Narančast, navlači se za <1 min, ne ometa pokretljivost, drži usta onesviještene osobe min. 12 cm iznad mora, reflektirajuće trake (zviždaljka za područje I i II).",
    pun: "Prsluk se navlači u najviše jednu minutu, ne ometa pokretljivost i omogućava da su usta onesviještene osobe u mirnom moru najmanje 12 cm iznad površine, te plivanje na kraćim udaljenostima. Narančaste je boje, sa samoreflektirajućim trakama (za područje plovidbe I i II i sa zviždaljkom). Na brodici mora biti dovoljno prsluka za svaku osobu." },
  { kat: "man", p: "Kako se pobrinuti za pothlađenu osobu?",
    kratko: "Reanimacija (i ako izgleda mrtva), podizati temperaturu, ne pomicati, mokru odjeću u suhu, tople napitke ako je svjesna. NE masirati, NE alkohol.",
    pun: "Hipotermija je gubitak unutrašnje temperature tijela. Prvu pomoć daj i kad izgleda da je osoba mrtva (organizam može hibernirati; oni koji ne drhte su u većoj opasnosti). Potrebno: provesti reanimaciju, podizati tjelesnu temperaturu, ne pomicati bolesnika, mokru odjeću zamijeniti suhom, davati tople napitke (ako je pri svijesti). NE masirati, NE davati alkohol." },
  { kat: "man", p: "Smije li se pothlađena osoba staviti uz jaki izvor topline?",
    kratko: "Ne naglo. Utopljavanje postupno (toplijim dijelovima tijela ili izvorima topline poput motora). Promrzle dijelove NE masirati.",
    pun: "Utopljavanje se provodi postupno (koristeći toplije dijelove tijela ili izvore topline poput brodskog motora), ne naglim izlaganjem jakom izvoru. Pojavom simptoma promrzlina (blijedilo, ukočenost) treba zahvaćene dijelove utopliti prije nego nastanu trajne posljedice; promrzle dijelove tijela ne smije se masirati." },

  // ===================== 5) RADIOTELEFONIJA =====================
  { kat: "rtf", p: "Koji broj zovemo za pomoć u slučaju pogibelji?",
    kratko: "195 (Središnjica za traganje i spašavanje, Rijeka); alternativa 112; ili VHF kanal 16.",
    pun: "Zovemo 195 (Središnjica za koordinaciju traganja i spašavanja u Rijeci), alternativa je 112, odnosno putem VHF radiotelefonske stanice – kanal 16." },
  { kat: "rtf", p: "Postoji li i drugi broj za pomoć?",
    kratko: "112 (opće uzbunjivanje) ili VHF kanal 16.",
    pun: "Alternativa je broj za opće uzbunjivanje 112, odnosno pomoć putem VHF radiotelefonske stanice – kanal 16." },
  { kat: "rtf", p: "Za koju vrstu nezgode koristimo PAN PAN?",
    kratko: "PAN PAN = poziv i poruka HITNOSTI.",
    pun: "PAN PAN se koristi za poziv i poruku hitnosti." },
  { kat: "rtf", p: "Fonetska tablica za sricanje (Alfa, Bravo…)?",
    kratko: "A-Alfa, B-Bravo, C-Charlie, D-Delta, E-Echo, F-Foxtrot, G-Golf, H-Hotel, I-India, J-Juliet, K-Kilo, L-Lima, M-Mike, N-November, O-Oscar, P-Papa, Q-Quebec, R-Romeo, S-Sierra, T-Tango, U-Uniform, V-Victor, W-Whiskey, X-X-Ray, Y-Yankee, Z-Zulu.",
    pun: "Međunarodna fonetska tablica: A Alfa, B Bravo, C Charlie, D Delta, E Echo, F Foxtrot, G Golf, H Hotel, I India, J Juliet, K Kilo, L Lima, M Mike, N November, O Oscar, P Papa, Q Quebec, R Romeo, S Sierra, T Tango, U Uniform, V Victor, W Whiskey, X X-Ray, Y Yankee, Z Zulu. Brojevi: 0 Nadazero, 1 Unaone, 2 Bissotwo, 3 Terrathree, 4 Kartefour, 5 Pantafive, 6 Soxisix, 7 Setteseven, 8 Oktoeight, 9 Novenine." },
  { kat: "rtf", p: "Kako tražiti pomoć ako nema radiostanice, mobitela i sl.?",
    kratko: "Signalima opasnosti: MAYDAY 3×, crvene rakete/buktinje, SOS, NC, narančasta plahta s kvadratom i krugom, dim, vatra, dizanje/spuštanje ruku, pucnjevi. Zrakoplovu: V/X.",
    pun: "Koriste se međunarodni signali opasnosti: MAYDAY triput, rakete s crvenim zvjezdicama, rakete s padobranom crvenog svjetla, ručne buktinje, SOS svjetlom/ogledalom/zvukom, slova NC, kvadratna zastava sa znakom kugle, narančasta jedrenina s crnim kvadratom i krugom, dim, vatra, dizanje i spuštanje ruku, pucnjevi svake minute, neprekinuto zvučno oglašavanje. Zrakoplovu: V (opća pomoć), X (medicinska)." },
  { kat: "rtf", p: "Koja su tri prioritetna poziva i za što služe?",
    kratko: "MAYDAY (pogibelj), PAN PAN (hitnost), SECURITE (sigurnost).",
    pun: "Tri prioritetna poziva: MAYDAY – pogibelj, PAN PAN – hitnost, SECURITE – sigurnost." },
  { kat: "rtf", p: "Što je poziv MEDICO (RADIO MEDICAL)?",
    kratko: "Hitan poziv za liječničku pomoć — obalna postaja povezuje brodicu s liječnikom; po potrebi evakuacija (kapetanija/helikopter).",
    pun: "MEDICO (Radio Medical) je hitan poziv vezan uz zdravstveno stanje osoba na plovilu; obalna postaja povezuje brodicu s liječnikom. Ako treba evakuacija, pomaže brodica lučke kapetanije ili (izuzetno) helikopterski prijevoz." },
  { kat: "rtf", p: "Što je PAN PAN?",
    kratko: "Poziv hitnosti.",
    pun: "PAN PAN je poziv hitnosti." },
  { kat: "rtf", p: "Što je MAYDAY, MAYDAY, MAYDAY?",
    kratko: "Poziv pogibelji — ima apsolutni prioritet.",
    pun: "MAYDAY je poziv pogibelji i ima apsolutni prioritet." },
  { kat: "rtf", p: "Što je HAKOM?",
    kratko: "Hrvatska regulatorna agencija za mrežne djelatnosti — dodjeljuje pozivni znak i MMSI za VHF stanicu (GMDSS Zona A1).",
    pun: "HAKOM (Hrvatska regulatorna agencija za mrežne djelatnosti) na upit dodjeljuje pozivni znak za VHF stanicu koja se ugrađuje na brodicu, te MMSI (Maritime Mobile Service Identity) za stanicu u sustavu GMDSS – Zona A1." },
  { kat: "rtf", p: "Koji su dijelovi radiotelefonske postaje?",
    kratko: "1) Predajnik+prijamnik+zvučnik s mikrofonom, 2) antenski kabel s antenom, 3) napajanje.",
    pun: "Brodska radijska postaja: 1) predajnik, prijamnik i zvučnik u cjelini s priključenim mikrofonom, 2) antenski kabel s antenom, 3) napajanje." },
  { kat: "rtf", p: "Što je GMDSS?",
    kratko: "Svjetski pomorski sustav za pogibelj i sigurnost (1992). Komponente: morske, kopnene, svemirske (GNSS, INMARSAT, COSPAS/SARSAT).",
    pun: "GMDSS (Global Maritime Distress and Safety System) – svjetski pomorski sustav za pogibelj i sigurnost (uspostavljen 1992). Zadaci: uzbunjivanje i komunikacija u pogibelji, poruke za sigurnost plovidbe, vođenje spašavanja, rutinska komunikacija. Komponente: morske (brodovi), kopnene (obalne postaje, centri za spašavanje, kapetanije), svemirske (GNSS, INMARSAT, COSPAS/SARSAT)." },
  { kat: "rtf", p: "MAYDAY, PAN PAN, SECURITE — što znače?",
    kratko: "MAYDAY – pogibelj; PAN PAN – hitnost; SECURITE – sigurnost.",
    pun: "Prioritetni pozivi VHF stanice: MAYDAY za poziv/poruku pogibelji, PAN PAN za hitnost, SECURITE za sigurnost." },
  { kat: "rtf", p: "Čemu služi VHF kanal 16 i koliko dugo smijemo biti na njemu?",
    kratko: "Kanal bdijenja i poziv pogibelji/hitnosti/sigurnosti (156,8 MHz). Pozivanje radi veze max 1 minuta. Prekršaj = kazna.",
    pun: "VHF kanal 16 (156,8 MHz) je kanal bdijenja i poziva pogibelji, hitnosti i sigurnosti. Pozivanje radi uspostave veze (koja nije pogibelj/hitnost/sigurnost) ne smije trajati duže od jedne minute. Nepoštivanje je pomorski prekršaj (novčana kazna) – jer kod VHF-a ne postoji 'vrijeme šutnje'." },
  { kat: "rtf", p: "Smije li se kanal 16 koristiti za uspostavu veze?",
    kratko: "Da, kad ne znaš radni kanal druge stanice — max 1 minuta, pa prekid par minuta i ponovni pokušaj.",
    pun: "Kanal 16 smije se, osim za prioritetne pozive, koristiti i za uspostavu veze kad ne znamo radni kanal druge stanice; poziv ne smije trajati duže od 1 minute. Ako se veza ne uspostavi, napravi se prekid od nekoliko minuta pa ponovni pokušaj." },
  { kat: "rtf", p: "Smije li se radiostanica koristiti unutar luke?",
    kratko: "Ne, osim za poruke važne za sigurnost plovidbe i komunikaciju s lučkim vlastima.",
    pun: "Uplovljavanjem u luku prestaje upotreba radiotelefonske postaje, osim za odašiljanje poruka važnih za sigurnost plovidbe i komunikaciju s lučkim vlastima." },
  { kat: "rtf", p: "Telefon Središnjice za traganje i spašavanje u Rijeci?",
    kratko: "195 (alternativa 112, ili VHF kanal 16).",
    pun: "Tel. broj Središnjice za koordinaciju traganja i spašavanja u Rijeci je 195, alternativa 112, odnosno putem VHF kanala 16." },
  { kat: "rtf", p: "Čemu služi SQ (squelch) na VHF stanici?",
    kratko: "Blokada šuma — otklanja šumove na prijemu (ne utječe na glasnoću). Propušta jače željene signale.",
    pun: "Squelch (blokada šuma) otklanja šumove i utječe samo na prijem signala (ne na glasnoću u zvučniku). Pravilno podešen sprječava primanje suvišnih slabih signala, a propušta željene jače signale." },
  { kat: "rtf", p: "Što znače tipke D/W i 1/25 na RTF stanici?",
    kratko: "D/W (Dual Watch) = istovremeno slušanje kanala 16 i drugog kanala. 1/25 W (L/H) = snaga emitiranja: slaba na blizinu, jaka na daljinu/u pogibelji.",
    pun: "D/W (Dual Watch) omogućava istovremeno slušanje kanala 16 i bilo kojeg drugog kanala (treperi 'CH 16'). Sklopka 1/25 W (ili L/H) podešava izlaznu snagu odašiljača – stanica mora moći prebacivati 25 W↔1 W. Prijenosne obično 1–5 W. Slabiju snagu koristimo na manjim udaljenostima, jaču na većim i u pogibelji/hitnosti/sigurnosti." },
  { kat: "rtf", p: "Čemu služi tipka DISTRESS na VHF DSC stanici?",
    kratko: "DSC (Digital Selective Call) šalje digitalni selektivni poziv preko kanala 70 (GMDSS). Aktivira 'zvono' pozvane stanice preko MMSI. Samo na ugrađenim VHF postajama.",
    pun: "DSC (Digital Selective Call) / DISTRESS tipka omogućuje slanje digitalnog selektivnog poziva preko VHF CH 70 u sustavu GMDSS – aktivira 'zvono' pozvane stanice preko MMSI broja (238 za HR + 6 znamenki). DSC kontrola ugrađena je isključivo na ugrađenim VHF postajama." },
  { kat: "rtf", p: "Kako se odašilje poziv i poruka pogibelji (primjer)?",
    kratko: "Na kanalu 16. Poziv: MAYDAY 3×, OVDJE, ime broda 3×. Poruka: MAYDAY 1×, ime, pozicija, vrsta pogibelji, tražena pomoć, broj osoba.",
    pun: "Poziv pogibelji ima apsolutni prioritet, odašilje se na kanalu 16. Poziv: MAYDAY 3×, riječ OVDJE, ime/pozivni znak 3×. Poruka: MAYDAY 1×, ime brodice, pozicija, vrsta pogibelji i tražena pomoć, ostale važne info. Primjer: 'MAYDAY, MAYDAY, MAYDAY, ovdje M/B MIRO, MIRO, MIRO, MAYDAY M/B MIRO, nalazimo se 1,5 M jugoistočno od svj. Blitvenica, imamo prodor vode i tonemo, TRAŽIM POMOĆ, na brodici 5 osoba, dvoje djece, nitko nije ozlijeđen, PRIJEM.'" },
  { kat: "rtf", p: "Primjer poziva hitnosti (PAN PAN) i sigurnosti (SECURITE)?",
    kratko: "PAN PAN: hitno za sigurnost broda/osobe (pad u more, kvar motora). SECURITE: navigacijsko/meteo upozorenje. Oba na kanalu 16, ponavljanje na radnom.",
    pun: "PAN PAN (hitnost) – osobito hitna poruka za sigurnost broda ili osobe (pad čovjeka u more, kvar motora). Primjer: 'PAN PAN ×3, svim brodovima ×3, ovdje M/B MIRO ×3, pozicija 43 25 N 15 43 E, imamo kvar motora, plutamo, trebamo tegljenje, PRIJEM.' SECURITE (sigurnost) ×3 – navigacijsko/meteo upozorenje (zapreka, magla, jak vjetar). Primjer: 'SECURITE ×3, svim brodovima ×3, ovdje M/B MIRO ×3, napuštena brodica pluta 4 M JI od svj. Sestrice, opasnost za plovidbu, PREKID.' Oba se odašilju na kanalu 16; duže/ponavljane poruke na radnom kanalu." },
  { kat: "rtf", p: "Smije li se na kanalu 16 govoriti bez ograničenja?",
    kratko: "Ne — pozivanje radi veze max 1 minuta; rezerviran za pogibelj/hitnost/sigurnost. Prekršaj = kazna.",
    pun: "Ne. Pozivanje radi uspostave veze ne smije trajati duže od jedne minute jer je kanal 16 rezerviran za pogibelj, hitnost i sigurnost. Nepoštivanje je pomorski prekršaj (novčana kazna) – zaštitna mjera jer kod VHF-a nema 'vremena šutnje'." },
  { kat: "rtf", p: "Kako se dobiva pozivni znak (call sign) i koji je predznak za HR?",
    kratko: "Dodjeljuje HAKOM. Predznak za Hrvatsku je 9A (+ 2–5 alfanumeričkih znakova).",
    pun: "Svaki brod/brodica s radijskom postajom ima znak raspoznavanja (pozivni znak). Prvi ili prva dva znaka označavaju državu, ostalih 2–5 alfanumeričkih dodjeljuju se plovilu. Znak za Hrvatsku je 9A." },
  { kat: "rtf", p: "Što je MMSI i koji je predznak za HR?",
    kratko: "Identifikacijski broj postaje (kao telefonski broj). HR predznak (MID) = 238 + 6 znamenki. Dodjeljuje HAKOM.",
    pun: "MMSI (Maritime Mobile Service Identity) je identifikacijski broj postaje u GMDSS-u (sličan telefonskom broju, komunikacija preko kanala 70). Sastoji se od troznamenkastog broja države (MID) – za HR je 238 – i 6-znamenkaste oznake (npr. 238 123456). Dodjeljuje HAKOM, pripada plovilu, programira ga dobavljač. Uz poziv pogibelji uz MMSI šalju se i koordinate (GNSS/GPS)." },
  { kat: "rtf", p: "Koliko kanala ima VHF stanica?",
    kratko: "57 kanala (1–28 i 60–88). Kanal bdijenja 16; kanal 70 za DSC pozive pogibelji.",
    pun: "VHF područje je 155–174 MHz. Ukupno 57 kanala (1–28 i 60–88). Međunarodni kanal bdijenja je 16, a kanal 70 služi za DSC pozive pogibelji u GMDSS-u." },
  { kat: "rtf", p: "Na kojoj je frekvenciji kanal 16 (i kanal 70)?",
    kratko: "Kanal 16 = 156,8 MHz. Kanal 70 (DSC) = 156,525 MHz. VHF područje 155–174 MHz.",
    pun: "Kanal 16 je na 156,8 MHz (poziv, pogibelj, hitnost, sigurnost), kanal 70 na 156,525 MHz (uzbunjivanje DSC u GMDSS-u). VHF radiofrekvencijsko područje je 155–174 MHz." },
  { kat: "rtf", p: "Što su simpleks, a što dupleks kanali?",
    kratko: "Simpleks: prijam i odašiljanje na istoj frekvenciji — naizmjenice ('PRIJEM'/'OVER', kraj 'GOTOVO'/'OVER AND OUT'). Dupleks: istovremeno kao telefon (treba 2 antene/filter).",
    pun: "Simpleksni kanal: prijamnik i odašiljač na istoj frekvenciji – sugovornici razgovaraju naizmjence, predaju riječ s 'PRIJEM' (OVER), a kraj razgovora 'GOTOVO' (OVER AND OUT). Dupleksni kanal: oba mogu govoriti istodobno kao telefon – treba VHF postaja s dvije antene ili dupleks filter (obično samo veća plovila)." },
  { kat: "rtf", p: "Koje zone postoje u GMDSS i koja oprema?",
    kratko: "A1 (do 30 M, VHF + VHF DSC), A2 (do 100 M, MF, 2182/2187,5 kHz, NAVTEX 518 kHz), A3 (70°N–70°S, INMARSAT, HF), A4 (polovi, HF + HF DSC).",
    pun: "Zona A1: do 30 M od obale – VHF i VHF DSC (kanali 6, 13, 16; navig. obavijesti kanal 13). Zona A2: do 100 M – MF i MF DSC (pogibelj 2182 kHz, uzbunjivanje 2187,5 kHz; NAVTEX 518 kHz). Zona A3: 70°N–70°S – satelitski INMARSAT i HF (4/6/8/12/16 MHz; 1,5/1,6 GHz), obavijesti EGC i HF MSI. Zona A4: od 70°N/70°S do polova – HF i HF DSC." },
  { kat: "rtf", p: "Kako se provjerava RTF stanica prije puštanja u rad?",
    kratko: "Antena (da ne dodiruje konstrukciju), akumulator (napunjen, dovoljan napon), primopredajnik (test tipkom za odašiljanje, prijam podešen squelchom).",
    pun: "Provjeri se: antenski sustav (antena ne smije dodirivati dijelove konstrukcije), akumulator (redovito punjen, dovoljan napon), primopredajnik (kontrola pritiscima na tipku za odašiljanje; prijam/smanjenje šuma podešava se SQUELCH-om)." },
  { kat: "rtf", p: "Što je EPIRB, a što SART plutača?",
    kratko: "EPIRB: radio-plutača (406 MHz, COSPAS/SARSAT) — emitira poziciju i MMSI 48 h. SART: radarski transponder — vidi se na radaru, 96 h prijem + 8 h predaje, min. 1 m iznad mora.",
    pun: "EPIRB (Emergency Position Indicating Radio Beacon): plutača koja na 406 MHz (sustav COSPAS/SARSAT, 12 satelita) emitira koordinate pozicije i MMSI, aktivira se ručno ili automatski u moru, radi 48 h. SART (Search and Rescue Transponder): radarski transponder čija se pozicija vidi kao odraz na radaru; napajanje 96 h u prijemu + 8 h predaje; pri korištenju min. 1 m iznad površine mora." },
];
